apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata: 
    name: dynamicipapp
spec:
    project: default
    destination:
       server: https://kubernetes.default.svc
       namespace: default 
    source:
       repoURL: https://github.com/ROHITkumaw/gitops_argocd.git
       path: prod
       targetRevision: main 

